name: NPM

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'
      - name: Open simple example
        run: cd examples/simple
      - name: Show directory content
        run: ls
      - name: Change package version for editor
        uses: MYXOMOPX/modify-pkg-json@master
        with:
          target: ./package.json
          save_to: ./dist/package.json
          action: 'set_devdep_version'
          argument: '@magic-circle/editor *'

      - name: Change package version for client
        uses: MYXOMOPX/modify-pkg-json@master
        with:
          target: ./package.json
          save_to: ./dist/package.json
          action: 'set_dep_version'
          argument: '@magic-circle/client *'
      - name: Output package json
        run: cat package.json
      - name: Setup repo
        run: npm ci
      - name: Run Magic Circle
        run: npm run build:editor
