name: Test

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'
      - name: Open simple example
        run: cd examples/simple
      - name: Change package version for editor
        run: jq '.devDependencies.@magic-circle/editor = "*"' package.json > "$tmp" && mv "$tmp" package.json
      - name: Change package version for client
        run: jq '.dependencies.@magic-circle/client = "*"' package.json > "$tmp" && mv "$tmp" package.json
      - name: Setup repo
        run: npm ci
      - name: Run Magic Circle
        run: npm run build:editor
