name: Release

# only deploy on release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install NPM dependencies
        run: npm ci

      # Get version number from package.json
      - name: Get version number
        id: version
        run: |
          VERSION=$(node -p -e "require('./lerna.json').version")
          echo "{version}={$VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Magic Circle ${{ steps.version.outputs.version }}
          draft: false
          prerelease: ${{contains(steps.version.outputs.version, 'alpha') || contains(steps.version.outputs.version, 'beta')}}
